import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Sidebar from "@/app/components/sidebar";
import {cn} from "@/lib/utils";
import {NextAuthProvider} from "@/providers/NextAuthProvider";
import {Toaster} from "@/components/ui/toaster";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body
        className={cn(
            `${geistSans.variable} ${geistMono.variable} antialiased`,
            "rounded-md flex flex-col md:flex-row bg-gray-100 dark:bg-neutral-800 w-full flex-1 mx-auto border border-neutral-200 dark:border-neutral-700 overflow-hidden",
            "h-screen"
        )}
    >
        <NextAuthProvider>
            <Sidebar/>
            <div className="flex flex-1 flex-col md:flex-row gap-6">
                <div
                    className="overflow-y-scroll p-4 md:p-8 rounded-2xl border border-neutral-200 dark:border-neutral-700 bg-white dark:bg-neutral-900 flex flex-col gap-4 flex-1">
                    {children}
                </div>
            </div>
            <Toaster />
        </NextAuthProvider>
    </body>
    </html>
);
}
